#!/bin/bash

BASE=`dirname $0`

IN_SRC_TREE="$BASE/robotkernel_gui.py"
if [ -f "$IN_SRC_TREE" ]; then
   exec "$IN_SRC_TREE" "$@"
fi

# rmpm-release - $0 is rk_base/bin/$(ARCH)/robotkernel_gui
IN_REL_TREE="$BASE/../../share/python/robotkernel_gui/robotkernel_gui.py"
if [ -f "$IN_REL_TREE" ]; then
   exec "$IN_REL_TREE" "$@"
fi

# local-install - $0 is rk_base/bin/robotkernel_gui
IN_REL2_TREE="$BASE/../lib/python/site-packages/robotkernel_gui/robotkernel_gui.py"
if [ -f "$IN_REL2_TREE" ]; then
   exec "$IN_REL2_TREE" "$@"
fi

echo "can not find robotkernel_gui.py!"
echo "tried  source tree location: $IN_SRC_TREE"
echo "tried release tree location: $IN_REL_TREE"
echo "tried release tree location: $IN_REL2_TREE"

exit -1
