Document: robotkernel
Title: Debian robotkernel Manual
Author: <insert document author here>
Abstract: This manual describes what robotkernel is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/robotkernel/robotkernel.sgml.gz

Format: postscript
Files: /usr/share/doc/robotkernel/robotkernel.ps.gz

Format: text
Files: /usr/share/doc/robotkernel/robotkernel.text.gz

Format: HTML
Index: /usr/share/doc/robotkernel/html/index.html
Files: /usr/share/doc/robotkernel/html/*.html
