#!/usr/bin/python

import sys

dlrrm_arch = sys.argv[1]

try:
    osver, mach, compiler = dlrrm_arch.split("-")

    if compiler.startswith("gcc"):
        compiler = "gnu" + compiler[3:]

    print "%s-%s-%s" % (mach, osver, compiler)
except:
    osver, mach, compiler, toolchain = dlrrm_arch.split("-")

    if compiler.startswith("gcc"):
        compiler = "gnu" + compiler[3:]

    print "%s-%s-%s" % (mach, osver, compiler)

